[tool.poetry]
name = "bolwerk"
version = "0.0.3"
description = "A Python tool for Terraform state summary and analysis"
authors = ["Rafael H de Carvalho <rafaelherik@gmail.com>"]
readme = "README.md"
repository = "https://github.com/rafaelherik/bolwerk"
documentation = "https://github.com/rafaelherik/bolwerk"
keywords = ["terraform", "infrastructure", "cloud", "DevOps"]
license = "MIT"
packages = [{include = "bolwerk"}]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/rafaelherik/bolwerk/issues"
"Source Code" = "https://github.com/rafaelherik/bolwerk"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pytest = ">=7.0.0"
pyyaml = ">=5.1"
jsonschema = ">=3.2.0"
colorama = ">=0.4.6"

[tool.poetry.group.dev.dependencies]
pytest-cov = ">=4.1.0"
pytest-mock = ">=3.6.1"
coverage = ">=7.2.0"

[tool.poetry.scripts]
bolwerk = "bolwerk.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

classifiers=[
"Development Status :: 3 - Alpha",
"Intended Audience :: Developers",
"License :: OSI Approved :: MIT License",
"Programming Language :: Python :: 3.10",
"Programming Language :: Python :: 3.11",
"Programming Language :: Python :: 3.12",
"Topic :: Software Development :: Build Tools",
"Topic :: System :: Systems Administration"
] 